# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParallelLineConstruction
                                 A QGIS plugin
 This plugin constructs parallel lines based on a given base line
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-02-28
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Stephan Donndorf
        email                : stephan@donndorf.info
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from qgis.gui import QgsMapToolEmitPoint
from qgis.core import QgsProject, QgsMapLayer, QgsWkbTypes

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .parallel_line_construction_dockwidget import ParallelLineConstructionDockWidget
import os.path


class ParallelLineConstruction:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ParallelLineConstruction_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Parallel Line Construction')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'ParallelLineConstruction')
        self.toolbar.setObjectName(u'ParallelLineConstruction')

        #print "** INITIALIZING ParallelLineConstruction"

        self.pluginIsActive = False
        self.dockwidget = None
        self.my_map_tool = None
        self.previous_map_tool = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ParallelLineConstruction', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/parallel_line_construction/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'ParallelLine Construction'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING ParallelLineConstruction"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD ParallelLineConstruction"

        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Parallel Line Construction'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING ParallelLineConstruction"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget is None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = ParallelLineConstructionDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

            self.previous_map_tool = self.iface.mapCanvas().mapTool()
            self.my_map_tool = QgsMapToolEmitPoint(self.iface.mapCanvas())
            self.my_map_tool.canvasClicked.connect(self.manage_click)
            self.iface.mapCanvas().setMapTool(self.my_map_tool)

            self.iface.mapCanvas().xyCoordinates.connect(self.update_coordinates)

            self.start_line_construction()

    def update_coordinates(self, pos):
        self.dockwidget.x_coord.setText("{:0.0f}".format(pos.x()))
        self.dockwidget.y_coord.setText("{:0.0f}".format(pos.y()))

    def manage_click(self, current_pos, clicked_button):
        if clicked_button == Qt.LeftButton:
            #self.dockwidget.remarks.setText("Clicked on {:0.0f} - {:0.0f}".format(current_pos.x(), current_pos.y()))
            #new_map_tool = QgsMapToolIdentify(self.iface.mapCanvas())
            #self.iface.mapCanvas().setMapTool(new_map_tool)
            #result = new_map_tool.identify(current_pos.x(), current_pos.y(), QgsMapToolIdentify.ActiveLayer)
            #self.dockwidget.remarks.setText("x:{}\ny:{}\n\nresult:{}\n".format(current_pos.x(), current_pos.y(), str(result)))
            #self.iface.mapCanvas().setMapTool(self.my_map_tool)
            self.start_line_construction()

        if clicked_button == Qt.RightButton:
            # reset to the previous mapTool
            self.iface.mapCanvas().setMapTool(self.previous_map_tool)
            # clean remove myMapTool and relative handlers
            self.my_map_tool = None

    def start_line_construction(self):
        # names for Layer Types
        LayerType = {
            QgsMapLayer.VectorLayer: "Vektor Layer",
            QgsMapLayer.RasterLayer: "Raster Layer",
            QgsMapLayer.PluginLayer: "Plugin Layer"
        }

        GeometryTypes = {

        }
        
        layers = QgsProject.instance().mapLayers()
        text = "Found {} layers in the map".format(len(layers))
        for layer in layers:
            text += "\n{} - type: {}".format(layers[layer].name(), LayerType[layers[layer].type()])
            if layers[layer].type() == 0:
                text += "\nGeometryType: {}".format(layers[layer].geometryType())
                if layers[layer].geometryType() == "line":
                    text += "\tThis is a line geometry!!! Yepeah..."
            text += "\n\tGot {} selected features".format(len(layers[layer].selectedFeatures()))

        active_layer = self.iface.activeLayer()
        if active_layer is None:
            text += "\n\nNo layer selected"
        else:
            text += "\n\n{}\n".format(active_layer.name())
            selected_features = self.iface.activeLayer().selectedFeatures()
            text += "Got {} selected features".format(len(selected_features))
            # for i in selected_features:
            #    attributes = i.attributeMap()
            #    for (k, attr) in attributes.iteritems():
            #        text += "{}: {}\n".format(k, attr)
        self.dockwidget.remarks.setText(text)

# for information, iterator over feature and attributes:
#
# features = iface.activeLayer().getFeatures()
# print(str([iface.activeLayer().attributeDisplayName(i) for i in iface.activeLayer().attributeList()]))
# for feature in features:
#     print(str([attr for attr in feature]))
#     #print([(iface.activeLayer().attributeDisplayName(i), feature[i]) for i in iface.activeLayer().attributeList()])